services: 
  nestjs:
    container_name: 'client_api_${NODE_ENV}'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: npm run start:$NODE_ENV
    env_file:
      - .env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    networks:
      - nestjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    container_name: 'mongodb_${NODE_ENV}'
    image: mongo
    ports:
      - '${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}'
    volumes:
      - 'nestjs-mongodb:/data/db'
    networks:
      - nestjs-network
networks:
  nestjs-network:
    driver: bridge
volumes:
  nestjs-mongodb:
    driver: local